name: cinelog-local

services:
  redis:
    image: redis:7-alpine
    container_name: cinelog_redis_local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:17-alpine
    container_name: cinelog_postgres_local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cinelog_db
      - POSTGRES_USER=cinelog
      - POSTGRES_PASSWORD=cinelog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinelog -d cinelog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinelog_db_migrate_local
    env_file:
      - .env
    volumes:
      - .:/app
      - api_venv:/app/.venv
    environment:
      - DATABASE_URL=postgresql+asyncpg://cinelog:cinelog@postgres:5432/cinelog_db
    command: sh -c "uv run alembic upgrade head"
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinelog_api_local
    ports:
      - "5009:5009"
    env_file:
      - .env
    volumes:
      - .:/app
      - api_venv:/app/.venv
    environment:
      - SMTP_SERVER=mailpit
      - SMTP_PORT=1025
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql+asyncpg://cinelog:cinelog@postgres:5432/cinelog_db
    command: sh -c "uv run uvicorn app:app --host 0.0.0.0 --port 5009 --reload --reload-dir app"
    depends_on:
      db-migrate:
        condition: service_completed_successfully
      mailpit:
        condition: service_started
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  email-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinelog_email_worker_local
    env_file:
      - .env
    volumes:
      - .:/app
      - api_venv:/app/.venv
    environment:
      - SMTP_SERVER=mailpit
      - SMTP_PORT=1025
      - DATABASE_URL=postgresql+asyncpg://cinelog:cinelog@postgres:5432/cinelog_db
    command: sh -c "uv run python worker.py"
    depends_on:
      db-migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_started

  mailpit:
    image: axllent/mailpit
    container_name: cinelog_mailpit_local
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI


volumes:
  redis_data:
  postgres_data:
  api_venv:
