name: Run Tests
on: [workflow_dispatch, pull_request]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:8
        ports:
          - 27017:27017
        options: >-
          --mount type=volume,source=mongo_data,target=/data/db
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install Dependencies
        run: pip3 install -r requirements.txt
      - name: Run Tests
        run: python3 -m pytest --cov=cinelog
